apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-django
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.django.settings.secretKey | b64enc | quote }}
  {{- if .Values.django.settings.saltKey }}
  salt-key: {{ .Values.django.settings.saltKey | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-database
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-geodatabase
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.geodatabase.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-storage
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.django.storage.accessKeyId | b64enc | quote }}
  secret-access-key: {{ .Values.django.storage.secretAccessKey | b64enc | quote }}
---
{{- if .Values.django.email.hostPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-email
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.django.email.hostPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.django.sentry.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qfieldcloud.fullname" . }}-sentry
  labels:
    {{- include "qfieldcloud.labels" . | nindent 4 }}
type: Opaque
data:
  dsn: {{ .Values.django.sentry.dsn | b64enc | quote }}
{{- end }} 